[package]
name = "plc-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
tokio-tungstenite = "0.23.1"
tungstenite = "0.23"
tokio-stream = "0.1"
futures-util = "0.3.30"
